param([int]$Jobs = 4, [switch]$Diagnostic, [string]$DiagnosticDirectory = 'out/recomp/diagnostic')
$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
$vswhere = Join-Path ${env:ProgramFiles(x86)} 'Microsoft Visual Studio\Installer\vswhere.exe'
if (-not (Test-Path -LiteralPath $vswhere)) { throw 'Visual Studio Installer/vswhere is required.' }
$vsRoot = & $vswhere -latest -products '*' -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
if (-not $vsRoot) { throw 'Visual Studio C++ desktop tools are required.' }
$vcvars = Join-Path $vsRoot 'VC\Auxiliary\Build\vcvars64.bat'
$compiler = Join-Path $env:ProgramFiles 'LLVM\bin\clang-cl.exe'
if (-not (Test-Path -LiteralPath $compiler)) { throw "Install LLVM with clang-cl at $compiler" }
# Import the compiler/SDK environment into this process only. The session
# keeps it, so a second run in the same window finds it there: running
# vcvars64 again would add to PATH each time until cmd refuses the line.
if ($env:VSCMD_ARG_TGT_ARCH -ne 'x64' -or -not $env:VCToolsInstallDir) {
    $environmentLines = & $env:COMSPEC /d /s /c "`"$vcvars`" >nul && set"
    if ($LASTEXITCODE -ne 0) { throw 'vcvars64 failed (if it says the input line is too long, open a new window).' }
    foreach ($line in $environmentLines) {
        if ($line -match '^([^=]+)=(.*)$') {
            [Environment]::SetEnvironmentVariable($Matches[1], $Matches[2], 'Process')
        }
    }
}
$llvmBin = Split-Path -Parent $compiler
if (-not $env:PATH.StartsWith($llvmBin + ';')) { $env:PATH = $llvmBin + ';' + $env:PATH }
$source = $repoRoot
$build = Join-Path $repoRoot 'out\build\host'
$diagnosticOption = if ($Diagnostic) { 'ON' } else { 'OFF' }
$diagnosticPath = [IO.Path]::GetFullPath((Join-Path $repoRoot $DiagnosticDirectory))
& cmake -S $source -B $build -G Ninja '-DCMAKE_BUILD_TYPE=Release' "-DCMAKE_C_COMPILER=$compiler" "-DCMAKE_CXX_COMPILER=$compiler" '-DCMAKE_POLICY_VERSION_MINIMUM=3.5' "-DSFR_BUILD_DIAGNOSTIC=$diagnosticOption" "-DSFR_DIAGNOSTIC_DIR=$diagnosticPath"
if ($LASTEXITCODE -ne 0) { throw 'Xenon tools configure failed.' }
$targets = @('XenonAnalyse', 'XenonRecomp', 'sfr_image_dump', 'sfr_memory_test', 'sfr_xex_module_test', 'sfr_virtual_memory_test', 'sfr_critical_section_test', 'sfr_hardware_info_test', 'sfr_thread_local_storage_test', 'sfr_system_time_test', 'sfr_guest_clock_test', 'sfr_timestamp_bundle_test')
$targets += 'sfr_vector_memory_test'
$targets += 'sfr_guest_entry_state_test'
$targets += 'sfr_guest_registers_test'
$targets += 'sfr_guest_function_table_test'
$targets += 'sfr_race_frame_clock_test'
$targets += 'sfr_race_orientation_hooks_test'
$targets += 'sfr_race_boarding_test'
$targets += 'sfr_race_scripted_motion_test'
$targets += 'sfr_race_launch_test'
$targets += 'sfr_job_lifetime_test'
$targets += 'sfr_debug_monitor_test'
$targets += 'sfr_nui_device_status_test'
$targets += 'sfr_nui_skeleton_test'
$targets += 'sfr_nui_menu_players_test'
$targets += 'sfr_nui_menu_progress_test'
$targets += 'sfr_nui_speech_test'
$targets += 'sfr_nui_race_test'
$targets += 'sfr_nui_race_players_test'
$targets += 'sfr_nui_race_hooks_test'
$targets += 'sfr_shader_inputs_test'
$targets += 'sfr_loop_constants_test'
$targets += 'sfr_vertex_palette_test'
$targets += 'sfr_unselected_users_test'
$targets += 'sfr_content_files_test'
$targets += 'sfr_touch_controls_test'
$targets += 'sfr_multibyte_unicode_test'
$targets += 'sfr_render_state_entries_test'
$targets += 'sfr_video_globals_test'
$targets += 'sfr_counted_branch_test'
$targets += 'sfr_image_protection_test'
$targets += 'sfr_optional_import_policy_test'
$targets += 'sfr_native_modules_test'
$targets += 'sfr_system_config_test'
$targets += 'sfr_native_language_test'
$targets += 'sfr_native_country_test'
$targets += 'sfr_system_country_test'
$targets += 'sfr_guest_critical_sections_test'
$targets += 'sfr_game_region_test'
$targets += 'sfr_integer_arithmetic_test'
$targets += 'sfr_store_halfword_update_test'
$targets += 'sfr_store_float_single_update_test'
$targets += 'sfr_load_halfword_update_test'
$targets += 'sfr_memory_update_forms_test'
$targets += 'sfr_vector_integer_test'
$targets += 'sfr_native_input_test'
$targets += 'sfr_input_trace_test'
$targets += 'sfr_input_bindings_test'
$targets += 'sfr_pad_assignment_test'
$targets += 'sfr_pad_devices_test'
$targets += 'sfr_camera_capture_test'
$targets += 'sfr_camera_android_lifecycle_test'
$targets += 'sfr_pose_estimator_test'
$targets += 'sfr_pose_skeleton_test'
$targets += 'sfr_pose_smoothing_test'
$targets += 'sfr_kinect_sensor_test'
$targets += 'sfr_kinect_stability_test'
$targets += 'sfr_pose_stability_test'
$targets += 'sfr_pause_gesture_test'
$targets += 'sfr_voice_commands_test'
# Checking a real Kinect without the game (docs/kinect-sensor.md).
$targets += 'sfr_kinect_probe'
$targets += 'sfr_pose_mediapipe_test'
$targets += 'sfr_camera_debug_test'
$targets += 'sfr_text_wrap_test'
$targets += 'sfr_camera_input_test'
$targets += 'sfr_camera_race_motion_test'
$targets += 'sfr_pipeline_cache_file_test'
$targets += 'sfr_shader_pack_format_test'
$targets += 'sfr_native_pipeline_key_test'
$targets += 'sfr_native_vertex_layout_test'
$targets += 'sfr_native_audio_test'
$targets += 'sfr_launcher_settings_test'
$targets += 'sfr_voice_language_test'
$targets += 'sfr_mod_loader_test'
$targets += 'sfr_vector_compare_bounds_test'
$targets += 'sfr_avatar_state_test'
$targets += 'sfr_gltf_model_test'
$targets += 'sfr_image_decode_test'
$targets += 'sfr_installer_test'
$targets += 'sfr_portable_waitables_test'
$targets += 'sfr_vulkan_shader_source_test'
$targets += 'sfr_launcher_art_test'
$targets += 'sfr_launcher'
$targets += 'sfr_texture_fetch_test'
$targets += 'sfr_memory_statistics_test'
$targets += 'sfr_video_mode_test'
$targets += 'sfr_physical_memory_test'
$targets += 'sfr_resource_coherency_test'
$targets += 'sfr_ansi_string_test'
$targets += 'sfr_native_sync_objects_test'
$targets += 'sfr_native_thread_test'
$targets += 'sfr_guest_execution_test'
$targets += 'sfr_guest_threads_test'
$targets += 'sfr_host_timing_test'
$targets += 'sfr_wait_trace_test'
$targets += 'sfr_host_core_plan_test'
$targets += 'sfr_vector_unpack_test'
$targets += 'sfr_native_timer_resolution_test'
$targets += 'sfr_native_constant_upload_test'
$targets += 'sfr_pipeline_manifest_test'
$targets += 'sfr_native_pipeline_prewarm_test'
$targets += 'sfr_guest_sync_objects_test'
$targets += 'sfr_native_named_sync_test'
$targets += 'sfr_guest_named_sync_test'
$targets += 'sfr_guest_wait_test'
$targets += 'sfr_asset_files_test'
$targets += 'sfr_async_asset_files_test'
$targets += 'sfr_pending_guest_write_test'
$targets += 'sfr_native_async_read_test'
$targets += 'sfr_async_completion_primitives_test'
$targets += 'sfr_guest_async_files_test'
$targets += 'sfr_guest_files_test'
$targets += 'sfr_guest_file_read_test'
$targets += 'sfr_native_graphics_test'
$targets += 'sfr_native_upload_batch_test'
$targets += 'sfr_native_shaders_test'
$targets += 'sfr_runtime_shader_pack_test'
$targets += 'sfr_native_presentation_test'
$targets += 'sfr_native_raster_state_test'
$targets += 'sfr_native_blend_control_test'
$targets += 'sfr_guest_graphics_test'
$targets += 'sfr_native_formats_test'
$targets += 'sfr_guest_render_state_test'
$targets += 'sfr_guest_blend_request_test'
$targets += 'sfr_guest_sampler_filter_test'
$targets += 'sfr_guest_texture_binding_test'
$targets += 'sfr_native_notification_event_test'
$targets += 'sfr_native_notifications_test'
$targets += 'sfr_notification_placement_test'
if ($Diagnostic) { $targets += 'sfr_cpu_diagnostic'; $targets += 'sfr_native_winsock_test' }
& cmake --build $build --target $targets --parallel $Jobs
if ($LASTEXITCODE -ne 0) { throw 'Xenon tools build failed.' }
